### ISSUE TITLE
บัตรผู้สูงอายุไม่มีลงวันหมดอายุ

### ISSUE THREAD

**Issue by RutNai** [chakphanu/ThaiNationalIDCard#3]
บัตรประชาชนผู้สูงอายุ วันบัตรหมดอายุเป็นตลอดชีพ ไม่มีลงวันหมดอายุทำให้ DateTime throw exception

Personal.cs
```
public DateTime Expire
        {
            get
            {
                return new DateTime(
                    Convert.ToInt32(_issue_expire.Substring(8, 4)) - 543,
                    Convert.ToInt32(_issue_expire.Substring(12, 2)),
                    Convert.ToInt32(_issue_expire.Substring(14, 2))
                    );
            }
        }
```
```
System.ArgumentOutOfRangeException was unhandled
  HResult=-2146233086
  Message=Year, Month, and Day parameters describe an un-representable DateTime.
  Source=mscorlib
  StackTrace:
       at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
       at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
       at ThaiNationalIDCard.Personal.get_Expire()
       at ThaiIdReader.Program.Main(String[] args) in D:\DotNetProject\ThaiIdReader\Program.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

**Comment by RutNai** [comment]
บัตรตลอดชีพ _issue_expire.Substring(8, 8) แสดงค่า 99999999
